spring:
  application:
    name: dev-ms-ucf-client
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui
    doc-expansion: none
  show-login-endpoint: true
server:
  port: 8889
  servlet:
    context-path: /${spring.application.name}
logging:
  file:
    name: /logs/ms-ucf-client.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

application:
  username: "admin"
  password: "a9165173-3c38-4c71-b8db-a8152a61f2a3"
  protocol: "http"
  host: "localhost"
  port: 8888
  getAllCompanies: ${application.protocol}://${application.host}:${application.port}/dev-ms-ucf/company/all
  getAllUsers: ${application.protocol}://${application.host}:${application.port}/dev-ms-ucf/user/all
  getAllDocuments: ${application.protocol}://${application.host}:${application.port}/dev-ms-ucf/document/all