spring:
  application:
    name: dev-ms-ucf-client
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui
    doc-expansion: none
  show-login-endpoint: true
server:
  port: 8889
  servlet:
    context-path: /${spring.application.name}
logging:
  file:
    name: /logs/ms-ucf-client.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

application:
  username: ""
  password: ""
  endpoint1: ""
  ednpoint2: ""
  endpoint3: ""